# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1eb96d416030e4fd05824019c996b499d0c5c680253bb6de9217099ba85f94255ad12560d70bcc5527579eaf18392ff9b7fd3cca3a5acf8433ba1ecf6ef7c50d

test:
  secret_key_base: 0b6c7d4d1f6278cbc9bba34c3bc87df7cf0d3c909a98fc411bbdcc319872db8888553451aac79da4d334b0b48ef7914d7d78f6050473a328dfd9c905f5946c57

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
